### ISSUE TITLE
Locale js Error

### ISSUE THREAD

**Issue by garhbod** [caouecs/Laravel4-SirTrevorJS#12]
The insertion of local failed as it's adding an extra slash to the path eg 'sir-trevor-js//locales/en.js'

**Comment by garhbod** [comment]
Line 172 of src/../SirTrevorJs.php amended by changing to 
            .HTML::script($config['path']."locales/".$config['language'].".js");
Rather than
            .HTML::script($config['path']."/locales/".$config['language'].".js");

**Comment by garhbod** [comment]
Stupid question as a side note. How do I actually insert an editor instance into a form in a blade template?

**Comment by caouecs** [comment]
Hello,
I fixed the problem of path : [762c644](https://github.com/caouecs/Laravel4-SirTrevorJS/commit/762c644084f8f0013390767c661ef2f063145c87)
